제어문이나 comprehension을 이용한 문제풀이


[문제1]  
리스트에 저장된 문자열 중에서 길이가 5인 것들만 리스트 형태로 출력하도록 구현하세요.  

a= ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']  

[출력결과]     
['alpha', 'bravo', 'delta', 'hotel', 'india']

In [1]:
a = ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']
answer = [word for word in a if len(word) == 5 ]
print(answer)

['alpha', 'bravo', 'delta', 'hotel', 'india']


[문제2]    
가로 크기를 저장한 리스트를 활용해서 가로 크기가 불규칙한  리스트를 생성하도록 프로그램을 구현하세요.

a = [3, 1,3, 2, 5]  


[출력결과]  
[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]


In [5]:
a = [3, 1, 3, 2, 5]
answer = [ [0 for _ in range(num)] for num in a ]
print(answer)

[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]


[문제3]    
포트폴리오의 총 비용을 계산하는 프로그램을 구현하세요.   

portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]     

[출력결과]  
44671.15

In [7]:
portfolio = [
    { 'name': 'AA', 'shares': 100, 'price': 32.20 },
    { 'name': 'IBM', 'shares': 50, 'price': 91.10 },
    { 'name': 'CAT', 'shares': 150, 'price': 83.44 },
    { 'name': 'MSFT', 'shares': 200, 'price': 51.23 },
    { 'name': 'GE', 'shares': 95, 'price': 40.37 },
    { 'name': 'MSFT', 'shares': 50, 'price': 65.10 },
    { 'name': 'IBM', 'shares': 100, 'price': 70.44 }
]

answer = [ p['shares'] * p['price'] for p in portfolio ]
print(sum(answer))

44671.15


[문제4]  
포트폴리오에서 100주 이상 보유한 종목의 리스트를 출력하는 프로그램을 구현하세요.    
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]  


[출력결과]    
[{'name': 'AA', 'shares': 100, 'price': 32.2},
 {'name': 'CAT', 'shares': 150, 'price': 83.44},
 {'name': 'MSFT', 'shares': 200, 'price': 51.23},
 {'name': 'IBM', 'shares': 100, 'price': 70.44}]


In [9]:

portfolio = [
    { 'name': 'AA', 'shares': 100, 'price': 32.20 },
    { 'name': 'IBM', 'shares': 50, 'price': 91.10 },
    { 'name': 'CAT', 'shares': 150, 'price': 83.44 },
    { 'name': 'MSFT', 'shares': 200, 'price': 51.23 },
    { 'name': 'GE', 'shares': 95, 'price': 40.37 },
    { 'name': 'MSFT', 'shares': 50, 'price': 65.10 },
    { 'name': 'IBM', 'shares': 100, 'price': 70.44 }
]

answer = [ p for p in portfolio if p['shares'] >= 100 ]
print(answer)

[{'name': 'AA', 'shares': 100, 'price': 32.2}, {'name': 'CAT', 'shares': 150, 'price': 83.44}, {'name': 'MSFT', 'shares': 200, 'price': 51.23}, {'name': 'IBM', 'shares': 100, 'price': 70.44}]


[문제5]

보유한 MSFT와 IBM주식 전체 리스트를 출력하는 프로그램을 구현하세요.  

portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]  

[출력결과]   
[{'name': 'IBM', 'price': 91.1, 'shares': 50},
 {'name': 'MSFT', 'price': 51.23, 'shares': 200},
 {'name': 'MSFT', 'price': 65.1, 'shares': 50},
 {'name': 'IBM', 'price': 70.44, 'shares': 100}]  



In [11]:
portfolio = [
    { 'name': 'AA', 'shares': 100, 'price': 32.20 },
    { 'name': 'IBM', 'shares': 50, 'price': 91.10 },
    { 'name': 'CAT', 'shares': 150, 'price': 83.44 },
    { 'name': 'MSFT', 'shares': 200, 'price': 51.23 },
    { 'name': 'GE', 'shares': 95, 'price': 40.37 },
    { 'name': 'MSFT', 'shares': 50, 'price': 65.10 },
    { 'name': 'IBM', 'shares': 100, 'price': 70.44 }
]

answer = [ p for p in portfolio if p['name'] == 'IBM' or p['name'] == 'MSFT' ]
print(answer)

[{'name': 'IBM', 'shares': 50, 'price': 91.1}, {'name': 'MSFT', 'shares': 200, 'price': 51.23}, {'name': 'MSFT', 'shares': 50, 'price': 65.1}, {'name': 'IBM', 'shares': 100, 'price': 70.44}]


[문제6]
보유 종목 중 가격이 10,000달러가 넘는 것의 리스트를 구현하는 프로그램을 구현하세요.  
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

[출력결과]    
[{'name': 'CAT', 'price': 83.44, 'shares': 150},
 {'name': 'MSFT', 'price': 51.23, 'shares': 200}]

In [12]:
portfolio = [
    { 'name': 'AA', 'shares': 100, 'price': 32.20 },
    { 'name': 'IBM', 'shares': 50, 'price': 91.10 },
    { 'name': 'CAT', 'shares': 150, 'price': 83.44 },
    { 'name': 'MSFT', 'shares': 200, 'price': 51.23 },
    { 'name': 'GE', 'shares': 95, 'price': 40.37 },
    { 'name': 'MSFT', 'shares': 50, 'price': 65.10 },
    { 'name': 'IBM', 'shares': 100, 'price': 70.44 }
]

answer = [ p for p in portfolio if p['shares'] * p['price'] >= 10000 ]
print(answer)

[{'name': 'CAT', 'shares': 150, 'price': 83.44}, {'name': 'MSFT', 'shares': 200, 'price': 51.23}]


[문제7]   
portfolio에서 얻은 name과 shares를 가지고 튜플의 리스트 (name, shares)를 만드는 프로그램을 구현하세요.  
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

[출력결과]   
[('AA', 100),
 ('IBM', 50),
 ('CAT', 150),
 ('MSFT', 200),
 ('GE', 95),
 ('MSFT', 50),
 ('IBM', 100)]



In [13]:
portfolio = [
    { 'name': 'AA', 'shares': 100, 'price': 32.20 },
    { 'name': 'IBM', 'shares': 50, 'price': 91.10 },
    { 'name': 'CAT', 'shares': 150, 'price': 83.44 },
    { 'name': 'MSFT', 'shares': 200, 'price': 51.23 },
    { 'name': 'GE', 'shares': 95, 'price': 40.37 },
    { 'name': 'MSFT', 'shares': 50, 'price': 65.10 },
    { 'name': 'IBM', 'shares': 100, 'price': 70.44 }
]

answer = [ (p['name'], p['shares']) for p in portfolio ]
print(answer)

[('AA', 100), ('IBM', 50), ('CAT', 150), ('MSFT', 200), ('GE', 95), ('MSFT', 50), ('IBM', 100)]


[문제8]  

리스트에서 int만 추출하는 프로그램을 구현하세요.  
oldlist = [1, 2, 'A', False, 3]

[출력결과]   
[1, 4, 9]  


In [14]:
oldlist = [1, 2, 'A', False, 3]
answer = [ old for old in oldlist if type(old) == int ]
print(answer)

[1, 2, 3]


[문제9]   
1부터 10까지의 홀수, 짝수로 출력하는 프로그램을 구현하세요.

[출력결과]   
{1: '홀수',
 2: '짝수',
 3: '홀수',
 4: '짝수',
 5: '홀수',
 6: '짝수',
 7: '홀수',
 8: '짝수',
 9: '홀수',
 10: '짝수'}


In [15]:
answer = { i: '홀수' if i % 2 == 1 else '짝수' for i in range(1, 11) }
print(answer)

{1: '홀수', 2: '짝수', 3: '홀수', 4: '짝수', 5: '홀수', 6: '짝수', 7: '홀수', 8: '짝수', 9: '홀수', 10: '짝수'}


 [문제10]  
 if~else문을 이용해서 년도에 해당하는 띠를 구하는 프로그램을 구현하시오.  
 단, 년도은 input()으로 입력받음.

   1. 12가지 띠  
      원숭이, 닭, 개, 돼지, 쥐, 소, 호랑이, 토끼, 용, 뱀, 말, 양  
   
   2. 띠구하는 공식  
     year%12의 결과가  
     0이면 "원숭이", 1이면 "닭"  2이면 "개",    3이면 "돼지",  
     4이면 "쥐",    5이면 "소", 6이면 "호랑이", 7이면 "토끼",  
     8이면 "용",    9이면 "뱀", 10이면 "말",   11이면 "양"  
     
   3. 출력결과  
     2012년도의 태생은  용띠입니다.  

In [18]:
year = int(input('년도 : '))
animal = ''

if (year % 12 == 0):
    animal = '원숭이'
elif (year % 12 == 1):
    animal = '닭'
elif (year % 12 == 2):
    animal = '개'
elif (year % 12 == 3):
    animal = '돼지'
elif (year % 12 == 4):
    animal = '쥐'
elif (year % 12 == 5):
    animal = '소'
elif (year % 12 == 6):
    animal = '호랑이'
elif (year % 12 == 7):
    animal = '토끼'
elif (year % 12 == 8):
    animal = '용'
elif (year % 12 == 9):
    animal = '뱀'
elif (year % 12 == 10):
    animal = '말'
else:
    animal = '양'

print(f'{year}년도의 태생은 {animal}띠입니다.')

2015년도의 태생은 양띠입니다.


[문제11]
list comprehension을 이용해서 1부터 10까지 합계 구하기

In [19]:
answer = [ i for i in range(1, 11) ]
print(sum(answer))

55


[문제12]
A 학급에 총 10명의 학생이 있다. 이 학생들의 중간고사 점수는 다음과 같다.

[70, 60, 55, 75, 95, 90, 80, 80, 85, 100]

list comprehension을 사용하여 A 학급의 평균 점수를 구해 보자.

In [ ]:
score = [70, 60, 55, 75, 95, 90, 80, 80, 85, 100]
answer = [ s / len(score) for s in score ]
print(sum(answer))

79.0


[문제13]
======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
> 1
메뉴명: 짜짜
가격: 3000
신규 메뉴 짜짜(이)가 등록되었습니다.
{'짜짜': '3000'}

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
> 2

==========메뉴판==========
짜짜 : 3000원
----------------------------------
1. 수정 | 2. 삭제 | 3. 나가기
> 3

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
> 3
프로그램을 종료합니다.

In [26]:
menuList = []

while True:
    print("""
======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료
""")
    
    selected = int(input())

    if (selected == 1):
        menuName = input('메뉴명 : ')
        menuPrice = int(input('가격 : '))

        newMenu = { menuName: menuPrice }
        menuList.append(newMenu)
        print(f'신규 메뉴 {menuName}이(가) 등록되었습니다.')
        print(newMenu)
    elif selected == 2:
        print('======메뉴판======')
        for menu in menuList:
            print(f'{list(menu.keys())[0]}: {list(menu.values())[0]}')

        print('----------------------------------')
        print('1. 수정 | 2. 삭제 | 3. 나가기')

        selected = int(input())

        if (selected == 3):
            continue
    else:
        print('프로그램을 종료합니다.')
        break


======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료

신규 메뉴 짜짜이(가) 등록되었습니다.
{'짜짜': 3000}

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료

======메뉴판======
짜짜: 3000
----------------------------------
1. 수정 | 2. 삭제 | 3. 나가기

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료

======메뉴판======
짜짜: 3000
----------------------------------
1. 수정 | 2. 삭제 | 3. 나가기

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료

신규 메뉴 스파게티이(가) 등록되었습니다.
{'스파게티': 2000}

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료

======메뉴판======
짜짜: 3000
스파게티: 2000
----------------------------------
1. 수정 | 2. 삭제 | 3. 나가기

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료

신규 메뉴 라면이(가) 등록되었습니다.
{'라면': 2000}

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료

======메뉴판======
짜짜: 3000
스파게티: 2000
라면: 2000
----------------------------------
1. 수정 | 2. 삭제 | 3. 나가기

======음식점 메뉴 관리 프로그램======
1. 신규 메뉴 등록
2. 메뉴판 전체 보기
3. 프로그램 종료

프로그램을 종료